export const metdata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

function RootLayout({children}:{children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}

export default RootLayout
